/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Score = IDL.Record({ 'score' : IDL.Nat, 'playerName' : IDL.Text });

export const idlService = IDL.Service({
  'createProfile' : IDL.Func([], [], []),
  'getAllScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'getMyHighScore' : IDL.Func([], [IDL.Nat], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'submitScore' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Score = IDL.Record({ 'score' : IDL.Nat, 'playerName' : IDL.Text });
  
  return IDL.Service({
    'createProfile' : IDL.Func([], [], []),
    'getAllScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'getMyHighScore' : IDL.Func([], [IDL.Nat], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'submitScore' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };